bio/urls.py
from . import views
from django.urls import path

app_name = 'bio'
urlpatterns = [
 
    path('<str:looking>/category/<str:slug>', views.view_cat, name='view_cat'),
    path('<str:looking>/service/<str:slug>', views.service_details, name='service_details'),
    path('<str:looking>/works/<str:slug>', views.work_details, name='work_details'),
    path('cv/<str:looking>', views.cv, name='cv'),    
    path('cv/<str:looking>/pdf', views.cvpdf, name='cvpdf'),
    
]

home/urls.py
from . import views
from django.urls import path
from django.views.generic.base import TemplateView
from .sitemaps import *
from django.contrib.sitemaps.views import sitemap


app_name = 'home'

sitemap_list = {
    'static': MySitemap,
    'cvsitemap' : CVSitemap,
    'looking': LookingSitemap,
    'firstlookcat': FirstLookCatSitemap,   
    'secondlookcat' : SecondLookCatSitemap,
    'firstlookservice' : FirstLookServiceDetails,
    'secondlookservice' : SecondLookServiceDetails,
    'firstlookworks' : FirstLookWorkDetails,
    'secondlookworks' : SecondLookWorkDetails,
    'senses': SensesDetailsSitemap,
    'sensestagsitemap' : SensesTagSitemap
    
    
    
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),      
    path('', views.home, name='home'),
    path('at/<str:looking>/', views.looking, name='looking'),
    path('elsifightbuilder/', TemplateView.as_view(template_name="home/elsifight.html"), name='elsifightbuilder'),   
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name='robot'), 
    
]

literature/urls.py
from . import views
from django.urls import path


app_name = 'literature'
urlpatterns = [ 
    path('home/', views.home, name='home'),  
    path('delete-idea/<int:pk>', views.delete_idea, name='delete_idea'),       
    path('configure_raw_story/<int:pk>/', views.generate_story_title_and_outline, name='generate_story_title_and_outline'),
    path('story_outline/<int:pk>/', views.story_outline, name='story_outline'),
    path('story/<int:pk>/', views.story, name='story')
]

home/models.py
from django.db import models

home/forms.py
from django import forms
from django.conf import settings
from pkg_resources import require

class LookingForm(forms.Form):     
    
   
    # looking_for = forms.ChoiceField(widget=forms.Select, choices=settings.LOOKING)
    looking_for = forms.ChoiceField(choices=settings.LOOKING, required=False, widget=forms.Select(attrs={'class': 'form-select', }))
    def clean(self):
        super().clean()
        looking_for = self.cleaned_data.get("looking_for")
    
        
        if not looking_for:
            msg = "You probably forgot to choose how I can help you!"
            self.add_error('looking_for', msg)
        

home/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import *
from bio.helper import get_me_data
from .decorators import looking_for_required, no_looking_required, set_looking_for
from common.common_processor import site_info, common_process
from django.template.defaultfilters import striptags
from common.common_processor import looking_list
from django.contrib import messages


def home(request):  
    looking_for = request.session.get('looking_for')
    
    redirect = HttpResponseRedirect(reverse('home:looking', kwargs={'looking': str(looking_for)}))             
    if request.session['looking_for'] not in looking_list():            
        pass
    else:
        return redirect   
    
    
         
    form = LookingForm()  
    if request.method == 'POST':
        form = LookingForm(request.POST)  
        if form.is_valid():
            looking = form.cleaned_data['looking_for']     
            if looking:                 
                request.session['looking_for'] = looking            
                return  HttpResponseRedirect(reverse('home:looking', kwargs={'looking': str(looking)}))
            else: 
                context = {                    
                    'form' : form     
                    }
                return render(request, 'home/index.html', context = context)
    context = {        
        'form' : form     
        }
    return render(request, 'home/index.html', context = context)

@set_looking_for
@looking_for_required
def looking(request, **kwargs): 
    looking = kwargs['looking']
    
    # if looking == 'None':
    #     messages.warning(request,f'Please choose the area from below...')            
    #     return HttpResponseRedirect('/')
     
    me_data = get_me_data(request)     
        
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(request.path),        
        'slogan' : f'Overview about me related to {looking} sector',
        'description' : f'{striptags(me_data.summary)[:160]}...',
        'topic' : f'{looking} overview ',
        'type' : f'My Overview',
        'robots' : f'index, follow',
        'og_image' : me_data.photo.url 
    }    
    seo_info.update(modify)   
    
    context = {
        'me_data': me_data,
        'alter' : reverse('home:looking', args=[str(common_process(request).get('alternat_looking'))]) ,
        'site' : seo_info,
    }
    return render(request, 'home/looking.html', context = context)

literature/views.py
import json
from pprint import pprint
import re
import time
import uuid
from django.conf import settings
from django.forms import formset_factory, inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
import openai
from home.decorators import superuser_required
from literature.forms import IdeaUtilizationForm, OutlineForm, StoryRawForm, StoryForm
from literature.models import Story, StoryOutline, StoryRaw
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import messages as msg
from django.contrib.auth.decorators import login_required

@superuser_required
def delete_idea(request, pk):
    story_raw = get_object_or_404(StoryRaw, pk=pk)
    idea = story_raw.idea
    idea.delete()
    
    return HttpResponseRedirect(reverse('literature:home'))

@login_required
@superuser_required
def home(request):
    q = request.GET.get('q')

    if q is not None:
        if len(q) < 3:
            msg.warning(request, 'At least 3 character required!')
            return HttpResponseRedirect(request.path)
        story_raws =  StoryRaw.objects.filter(Q(idea__idea__icontains=q) | Q(title__icontains=q) | Q(genre__icontains=q) | Q(type__icontains=q)).order_by('-created')
    else:    
        story_raws = StoryRaw.objects.all().order_by('-created')
    
    form = IdeaUtilizationForm()   
     
    paginator = Paginator(story_raws, 10)
    page = request.GET.get('page')     
    
    try:
        story_raws = paginator.page(page)
    except PageNotAnInteger :
        story_raws = paginator.page(1)
    except EmptyPage:
        story_raws = paginator.page(paginator.num_pages)  
        
        
    if request.method == 'POST':
        form = IdeaUtilizationForm(request.POST)  
        if form.is_valid():
            idea  = form.save(commit=False)
            
            prompt = {
                'prompt': f'Based on the idea above please suggest the following in the format below:\n\n'
                        f'Title:"""insert title here. Avoid "\n" character instead use comma""", '
                        f'Genre:"""insert genre here. Avoid "\n" character instead use comma""", '
                        f'Type:"""insert type here. Avoid "\n" character instead use comma""", '
                        f'Character:"""insert character here. Avoid "\n" character instead use comma""", '
                        f'Setting:"""insert settings here. Avoid "\n" character instead use comma""", '
                        f'Conflict:"""insert conflict here. Avoid "\n" character instead use comma""", '
                        f'Tone:"""insert tone here. Avoid "\n" character instead use comma""", '
                        f'Style:"""insert style here. Avoid "\n" character instead use comma""", '
                        f'Topic:"""inset topic here. Avoid "\n" character instead use comma""", '
                        f'Purpose:"""insert purpose here. Avoid "\n" character instead use comma""", '
                        f'Audience:"""insert audience here. Avoid "\n" character instead use comma""", '
                        f'Key points:"""insert key points here. Avoid "\n" character instead use comma""", '
                        f'Theme:"""insert theme here. Avoid "\n" character instead use comma""", '
                        f'Mood:"""insert mood here. Avoid "\n" character instead use comma""", '
                        f'Species:"""insert species here. Avoid "\n" character instead use comma""", '
                        f'Quest:"""insert quest here. Avoid "\n" character instead use comma""", '                        
            }

            messages = []

            messages.append({'role': 'system', 'content': "You are a helpful assistant focused on suggesting appropriate parameters for writing literature. Your duty is to perform deep analysis and provide relevant suggestions in creative manners."})
            messages.append({'role': 'user', 'content': f"This is the plot:\n\n'''{form.cleaned_data['idea']}'''"})
            messages.append({'role': 'user', 'content': f"{prompt}"})  # Send prompt as a regular user message

            response = generate_from_chatgpt(messages, temp=1)
            print('response_____________________')
            pprint(response)
                  
            try:
                # Split the response text into lines
                response_lines = response.split('\n')
                
                print('response_lines____________________')
                print(response_lines)
                
                # Initialize an empty dictionary to store the structured data
                structured_data = {}

                # Loop through the response lines and populate the dictionary
                for line in response_lines:
                    try:
                        print('line_________________________')
                        print(line)
                        
                        key, value = line.split(': ', 1)
                        print('key, value__________________________________________')
                        print(key, value)
                        
                        structured_data[key] = value
                    except Exception as e:
                        print(f"problem in unpack {e}")
                        continue
                print('structured_data__________________________________')
                print(structured_data)
                
                # Convert the structured data into JSON format
                
                json_data = json.dumps(structured_data, indent=4)
                print('json_data_____________________')
                print(json_data)
                
                idea.idea_response = json_data
                idea.save()
                
                data = json.loads(idea.idea_response)
                
                print('data________________________________')
                print(data)
                
                
                story_raw = idea.storyraw
                
                story_raw.title= data.get('Title')
                story_raw.tenre= data.get('Genre')
                story_raw.type= data.get('Type')
                story_raw.character= data.get('Character')
                story_raw.setting= data.get('Setting')
                story_raw.conflict= data.get('Conflict')
                story_raw.tone= data.get('Tone')
                story_raw.style= data.get('Style')
                story_raw.topic= data.get('Topic')
                story_raw.purpose= data.get('Purpose')
                story_raw.audience= data.get('Audience')
                story_raw.key_points= data.get('Key points')
                story_raw.theme= data.get('Theme')
                story_raw.mood= data.get('Mood')
                story_raw.species= data.get('Species')
                story_raw.quest= data.get('Quest')
                
                story_raw.save()
                
            except Exception as e:
                print(f"the proem occured due to: {e}")
                raise ValueError(f'imappropriate value from response:{e}')  
            
            
            return HttpResponseRedirect(reverse('literature:generate_story_title_and_outline', args=[int(story_raw.pk)]))
        
    
    context = {
        'story_raws' : story_raws,
        'form' : form
    }
    
    
    return render(request, 'literature/home.html', context)
    
@login_required
@superuser_required
def generate_from_chatgpt(messages, temp):
    openai.api_key = settings.OPENAI_API_KEY
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=messages,
        temperature=temp
    )
    return response['choices'][0]['message']['content']


@login_required
@superuser_required
def generate_story_title_and_outline(request, pk):
    story_raw_id = pk  
    
    story_raw_obj = get_object_or_404(StoryRaw, pk=story_raw_id)
        
    idea_res = json.loads(story_raw_obj.idea.idea_response)
    # idea_res = story_raw_obj.idea.idea_response
    
    
    poem_indicator = ['poem', 'Poem', 'Poetry']    
    if request.method == 'POST':
            
        story_raw_form = StoryRawForm(request.POST, instance = story_raw_obj)
            
        if story_raw_form.is_valid():
            
            cleaned_data = story_raw_form.cleaned_data
            
            genre = cleaned_data.get('genre')
            character = cleaned_data.get('character')
            type = cleaned_data.get('type')
            setting = cleaned_data.get('setting')
            conflict = cleaned_data.get('conflict')
            tone = cleaned_data.get('tone')
            style = cleaned_data.get('style')
            topic = cleaned_data.get('topic')
            purpose = cleaned_data.get('purpose')
            audience = cleaned_data.get('audience')
            key_points = cleaned_data.get('key_points')
            theme = cleaned_data.get('theme')
            mood = cleaned_data.get('mood')
            rhyme_meter = cleaned_data.get('rhyme_meter')
            imagery_symbolism = cleaned_data.get('imagery_symbolism')
            characters = cleaned_data.get('characters')
            scenes = cleaned_data.get('scenes')
            dialogue = cleaned_data.get('dialogue')
            world_building = cleaned_data.get('world_building')
            species = cleaned_data.get('species')
            quest = cleaned_data.get('quest')
            crime = cleaned_data.get('crime')
            detective = cleaned_data.get('detective')
            clues_red_herrings = cleaned_data.get('clues_red_herrings')
            historical_figures = cleaned_data.get('historical_figures')
            character_arcs = cleaned_data.get('character_arcs')
            meet_cute = cleaned_data.get('meet_cute')

templates/literature/create_story_home.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}



  {% block stylesheets %}



  {% endblock stylesheets %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-95">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center text-danger my-4">
                <h1 class="mb-4">We are writing {{story_raw_obj.title}} || {{story_raw_obj.genre}} || {{story_raw_obj.type}} </h1>                
                
            </div>
        </div>
        
    </div>

    

</section>

<section class="pt-6 bg-light o-95">
    <div class="container mt-n10 mt-n11 z-2">
        <div class="row justify-content-center align-items-center">
            <div class=" card shadow col-12 p-5 o-90">

                <div class="d-flex justify-content-between mb-2">                    
                    <div>
                        <div class="h4">Below are the idea was inputed</div>
                        <small>If you want to recreate configuration then please delete this and write again.</small>
                    </div>    
                    <div>
                    <a href="{% url 'literature:delete_idea' story_raw_obj.pk %}" class="btn btn-danger">Delete Idea</a>   </br>
                    <small>It will remove all genarated data and non recorable</small>
                    </div>             
                </div>

                <div class="alert alert-dark">
                    {{story_raw_obj.idea.idea|linebreaksbr}}
                </div>


                
                

                <div class="alert alert-primary">
                    Below configurationd data genarated by system and probably it has benn placed in the configuration interface below. You can modify as you wise.
                </div>

                

                <div class="alert alert-dark">
                    {% for key, value in idea_res.items %}
                    <b>{{ key }}</b> : {{value}} </br>
                    {% endfor %}
                </div>

                <div class="d-flex justify-content-between">                    
                    <h2>Configuration</h2>                    
                </div>
                <div>
                    <small>Based on the configuration below, an outline of the literature will be created. A perfect configuration can provide you with a flawless outline for writing a portion of literature.</small>
                </div>

                <form class="row justify-content-center" method="POST" action="">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="col-md-6 col-xl-4 d-flex">
                            <div class="card bg-silver bg-gradient my-2 p-2 flex-fill" >
                                {{ field.errors }}
                                {{ field.label_tag }} {{ field }}
                                {% if field.help_text %}
                                    <p class="help">{{ field.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="btn-group">
                    
                    {% if story_raw_obj.has_outline %}
                        <a href="{% url 'literature:story_outline' story_raw_id %}" class="btn btn-warning btn-block">Go To Outline</a>  
                        <input type="submit" id="raw_form" name="regenarate_outline"  class="btn btn-danger btn-block" value = "Re Generate Outline"/> 
                    {% elif not story_raw_obj.has_outline  %} 
                        <input type="submit" id="raw_form" name="modify_and_stay" class="btn btn-warning btn-block" value = "Modify And Stay"/> 
                        <input type="submit" id="raw_form" name="genarate_outline" class="btn btn-success btn-block" value = "Generate Outline"/> 
                    {% endif %}
                    {% if story_raw_obj.has_story  %}  
                        <a href="{% url 'literature:story' story_raw_id %}" class="btn btn-warning btn-block">Go To Story</a>  
                    {% endif %}
                    </div>

                </form>
                <div><small>If you wish to make any changes to the configuration, it is recommended to do so before generating the outline by clicking the "Modify and Stay" button. Once the outline is generated, you will need to regenerate it if you make any changes. </small></div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block javascripts %}



{% endblock javascripts %}

templates/literature/story.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}



  {% block stylesheets %}



  {% endblock stylesheets %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-95">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center text-danger my-4">
                <h1 class="mb-4">Latest Senses</h1>                
                
            </div>
        </div>

        {% if messages %}
        <div class="alert alert-secondary mt-5 text-center" role="alert">
            {% for message in messages %}
            <span class="alert-inner--text ">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>



</section>

<section class="pt-6 bg-light o-95">
    <div class="container mt-n10 mt-n11 z-2">
        <div class="row justify-content-center align-items-center">
            <div class=" card shadow col-12 p-5 o-90">
                <div class="row">   
                         
                <div class="col-md-8 col-lg-9 mx-auto">
                    
                    <form method="post">
                        {% csrf_token %}
                        {{ formset.management_form }}
                        {% for form in formset %}                     
                            {{form}}
                        {% endfor %}
                        <div class="btn btn-group">
                            <a href="{% url 'literature:generate_story_title_and_outline' story_raw.pk %}" class="btn btn-warning btn-block">Back to Config</a>  
                            <a href="{% url 'literature:story_outline' story_raw.pk %}" class="btn btn-light btn-block">Back to Outline</a>  
                            <input class="btn btn-success" type="submit" value="Save">
                        </div>
                    </form>


                
                </div>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

{% block javascripts %}


<script>
    $(document).ready(function() {
        // Function to adjust the number of rows for Textarea fields
        function adjustTextareaRows() {
            $('textarea').each(function() {
                var textarea = $(this);
                var lineHeight = parseInt(textarea.css('line-height'));
                var currentRows = textarea.prop('rows');
                var newRows = Math.ceil(textarea[0].scrollHeight / lineHeight);
                if (newRows !== currentRows) {
                    textarea.prop('rows', newRows);
                }
            });
        }
    
        // Call the function on document ready and when the window is resized
        adjustTextareaRows();
        $(window).resize(adjustTextareaRows);
    });
    </script>

{% endblock javascripts %}

templates/literature/story_raw_outline.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}



  {% block stylesheets %}



  {% endblock stylesheets %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-95">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center text-danger my-4">
                <h1 class="mb-4">We are writing {{story_raw.title}} || {{story_raw.genre}} || {{story_raw.type}} </h1>                
               
            </div>
        </div>

        {% if messages %}
        <div class="alert alert-secondary mt-5 text-center" role="alert">
            {% for message in messages %}
            <span class="alert-inner--text ">{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>



</section>

<section class="pt-6 bg-light o-95">
    <div class="container mt-n10 mt-n11 z-2">
        <div class="row justify-content-center align-items-center">
            <div class=" card shadow col-12 p-5 o-90">
                <div class="row">   
                         
                <div class="col-md-8 col-lg-9 mx-auto">
                    <form method="POST" action="">
                            {% csrf_token %}
                            {{ formset.management_form }}
                            {% for form in formset %}
                                <div class="mb-2 border-bottom border-2 border-danger py-3">
                                    {% for field in form %}                                    
                                            <div class="form-group">
                                                <!-- Label without colon -->  
                                                {% if not field.is_hidden %}    
                                                    <label for="{{ field.id_for_label }}" class="h4">{{ field.label }}</label>   
                                                {% endif %}                                
                                                <!-- Form field -->
                                                {{ field }}
                                                <!-- Help text -->
                                                <div>
                                                    <small class="form-text text-muted">{{ field.help_text }}</small>
                                                </div>
                                            </div>      
                                            {% for error in field.errors %}
                                                <div class="text-danger">{{ error }}</div>
                                            {% endfor %}
                                        
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <div class="btn-group">
                                <a href="{% url 'literature:generate_story_title_and_outline' story_raw.pk %}" class="btn btn-warning btn-block">Back To Configuration</a> 
                                {% if not story_raw.has_story %} 
                                <input type="submit" id="outline_form"  name="save_and_stay"  class="btn btn-dark btn-block" value = "Save And Stay"/>

                                <input type="submit" id="outline_form"  name="regenarate_story"  class="btn btn-success btn-block" value = "Genarate Story"/>

                                {% endif %}
                                {% if story_raw.has_story %}
                                <input type="submit" id="regenarate" name="regenarate_story" class="btn btn-danger btn-block" value = "Re Genarate Story"/>
                                <a href="{% url 'literature:story' story_raw.pk %}" class="btn btn-warning btn-block">Go To Story</a>  
                                {% endif %}

                            </div>                            
                        </form>
                
                </div>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

{% block javascripts %}

<script>
    $(document).ready(function() {
        // Function to adjust the number of rows for Textarea fields
        function adjustTextareaRows() {
            $('textarea').each(function() {
                var textarea = $(this);
                var lineHeight = parseInt(textarea.css('line-height'));
                var currentRows = textarea.prop('rows');
                var newRows = Math.ceil(textarea[0].scrollHeight / lineHeight);
                if (newRows !== currentRows) {
                    textarea.prop('rows', newRows);
                }
            });
        }
    
        // Call the function on document ready and when the window is resized
        adjustTextareaRows();
        $(window).resize(adjustTextareaRows);
    });
    </script>

{% endblock javascripts %}