bio/urls.py
from . import views
from django.urls import path

app_name = 'bio'
urlpatterns = [
 
    path('<str:looking>/category/<str:slug>', views.view_cat, name='view_cat'),
    path('<str:looking>/service/<str:slug>', views.service_details, name='service_details'),
    path('<str:looking>/works/<str:slug>', views.work_details, name='work_details'),
    path('cv/<str:looking>', views.cv, name='cv'),    
    path('cv/<str:looking>/pdf', views.cvpdf, name='cvpdf'),
    
]

home/urls.py
from . import views
from django.urls import path
from django.views.generic.base import TemplateView
from .sitemaps import *
from django.contrib.sitemaps.views import sitemap


app_name = 'home'

sitemap_list = {
    'static': MySitemap,
    'cvsitemap' : CVSitemap,
    'looking': LookingSitemap,
    'firstlookcat': FirstLookCatSitemap,   
    'secondlookcat' : SecondLookCatSitemap,
    'firstlookservice' : FirstLookServiceDetails,
    'secondlookservice' : SecondLookServiceDetails,
    'firstlookworks' : FirstLookWorkDetails,
    'secondlookworks' : SecondLookWorkDetails,
    'senses': SensesDetailsSitemap,
    'sensestagsitemap' : SensesTagSitemap
    
    
    
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),      
    path('', views.home, name='home'),
    path('at/<str:looking>/', views.looking, name='looking'),
    path('elsifightbuilder/', TemplateView.as_view(template_name="home/elsifight.html"), name='elsifightbuilder'),   
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name='robot'), 
    
]

sense/urls.py
from . import views
from django.urls import path


app_name = 'sense'
urlpatterns = [ 
    path('senses/', views.post_list, name='sense_list'),
    path('senses/<str:slug>', views.post_detail, name='sense_detail'),
    path('senses/tag/<str:slug>', views.post_list, name='sense_tag'),       
]

templates/layouts/ads_boom_your_identity.html
<script src="https://gumroad.com/js/gumroad.js"></script>
<a class="gumroad-button" href="https://haradhan.gumroad.com/l/boom-your-identity">Buy BOOM YOUR IDENTITY on</a>

templates/layouts/ads_inarticle.html
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6547428806314947"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
    style="display:block; text-align:center;"
    data-ad-layout="in-article"
    data-ad-format="fluid"
    data-ad-client="ca-pub-6547428806314947"
    data-ad-slot="4887468123"
    data-adtest="on"
    data-adbreak-test="on"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

templates/layouts/ads_infeed.html
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6547428806314947"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-gw-3+1f-3d+2z"
     data-ad-client="ca-pub-6547428806314947"
     data-ad-slot="2233099213"
     data-adtest="on"
    data-adbreak-test="on"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

templates/layouts/ads_multiplex.html
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6547428806314947"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="autorelaxed"
     data-ad-client="ca-pub-6547428806314947"
     data-ad-slot="1678850859"
     data-adtest="on"
     data-adbreak-test="on"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

templates/layouts/ads_propellerads_Interstitial.html
<script async="async" data-cfasync="false" src="//upgulpinon.com/1?z=5217226"></script>

templates/layouts/ads_rakuten_jone_academy_horizontal.html
<a href="https://click.linksynergy.com/fs-bin/click?id=PiSwZl1GQ5E&offerid=690746.15&subid=0&type=4" rel="nofollow">
    <IMG border="0"   alt="John Academy" src="https://ad.linksynergy.com/fs-bin/show?id=PiSwZl1GQ5E&bids=690746.15&subid=0&type=4&gridnum=16"></a>

templates/layouts/ads_seranking.html
<iframe src="https://online.seranking.com/affiliatewidget.html?id=1908437&lang=en&full=1&small=1" frameborder="0" width="100%" height="140px"></iframe>

templates/layouts/googlescripts.html
<!-- Global site tag (gtag.js) - Google Analytics -->

<script async src="https://www.googletagmanager.com/gtag/js?id=G-T7NTD1KPGX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-T7NTD1KPGX');
</script>

templates/layouts/pagination.html
{% if page.has_other_pages %}
<ul class="pagination mt-3 mb-0">
  {% if page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
  {% else %}
    <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
  {% endif %}
  {% for i in page.paginator.page_range %}
    {% if page.number == i %}
      <li class="active page-item"><span class="page-link">{{ i }}</span></li>
    {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a></li>
  {% else %}
    <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}

templates/layouts/scripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>


<script>
    document.body.addEventListener('htmx:configRequest', (e) => {
      e.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
</script>
<script>
  AOS.init();
</script>

templates/layouts/tophero.html
{% load static %}
<div class="bg-myblack bg-gradient p-4 text-light o-95">
    <div class="container py-5">
        <div class="row d-xl-flex justify-content-center">
            <div data-aos="fade-right" data-aos-duration="3000" class="col-6 col-sm-4 col-md-3 col-xl-2">
                <img src="{% static me_data.photo.url %}" class="rounded img-thumbnail"  alt="{{me_data.title}}">
            </div>
            <div data-aos="fade-down" data-aos-duration="3000" class="col-12 col-xl-10 text-center text-xl-start">
                <div class="fs-5 text-danger mb-1">Hi, my name is___</div>
                <h2 class="fs-3 fw-bold m-0 ">{{me_data.title|upper}}</h2>
                <div class="fs-6 text-brightbeige mt-2">{{me_data.summary|safe}}</div>
                <div  data-aos="fade-left" data-aos-duration="3000" class="mt-2">
                    {% for link in me_data.get_links %}
                    <a class="btn btn-secondary bg-gradient btn-sm mb-1" target="_blank" rel="dofollow" href="{{link.links}}"><span>{{link.icon|safe}}</span></a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/layouts/v2_base_footer.html
<div class="container-fluid bg-light mt-4">
    <div class="container">
        <div class="row text-center align-items-center justify-content-center mb-4 mt-4">
            <div class="">
                <div class="mt-4">
                    {% include "layouts/ads_webhostingpad.html" %}
                </div>
                <div class="mt-4">
                    {% include "layouts/ads_seranking.html" %}
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <div class="row text-center align-items-center justify-content-center mb-4">
            <div class="footer-menu">
                {% for name, path in footer_menu.items %}
                <a href="{{path}} " class="me-2 {% if request.path == path %} border-bottom {% endif %}">{{name}}</a>
                {% endfor %}
                <a href="https://selfurl.xyz/bnhnaqixfo" target="_blank"
                    class="me-2 {% if request.path == path %} border-bottom {% endif %}">Secure Digital Life</a>
                <a href="https://selfurl.xyz/cglgvqloba" target="_blank"
                    class="me-2 {% if request.path == path %} border-bottom {% endif %}">Elsifight</a>
            </div>
            <p>&copy; All Right Reserved By <a href="https://hrdnsh.com/" class="text-primary">{{site.domain}}</a>,
                Developed by <a href="https://hrdnsh.com" class="text-warning">Haradhan Sharma</a>.</p>
        </div>
    </div>
</footer>

templates/layouts/v2_base_full_header.html
{% load static %}
<header class="mb-auto">
        <div class="d-flex justify-content-between">
                <h3 data-aos="zoom-in-down" class=" mb-0">
                        <a href="/">
                                <img src="{% static site.logo %}" height="40" alt="{{ site.name }}">
                        </a>
                </h3>
                <div class="text-end justify-content-end align-items-end">
                        <a href="{% url 'sense:sense_list' %}"
                                class="mb-0 py-sm-0 py-md-2 px-sm-0 px-md-2 text-decoration-none d-block d-md-inline-block">Senses</a>
                        <a href="{% url 'home:elsifightbuilder' %}" target="_blank"
                                class="mb-0 py-sm-0 py-md-2 px-sm-0 px-md-2 text-decoration-none d-block d-md-inline-block {% if  request.path == path %} active {% endif %} ">
                                <svg width="20" height="20" id="Layer_1" data-name="Layer 1"
                                        xmlns="http://www.w3.org/2000/svg" viewBox="0 0 243.96 234.86">
                                        <defs>
                                                <style>
                                                        .cls-1 {
                                                                fill: #ef3c65;
                                                        }

                                                        .cls-2 {
                                                                fill: #ef3a65;
                                                        }
                                                </style>
                                        </defs>
                                        <title>Elsifight</title>
                                        <path class="cls-1"
                                                d="M425.43,253.62c-.16,59.07-44.16,109.08-102.18,116.75-63.81,8.43-123.56-37.61-131.53-101.22a159.82,159.82,0,0,1-.68-24.94,25.46,25.46,0,0,1,.93-5.91c1.9-6.9,7.21-10.69,13.15-9.55,6.37,1.23,9.88,6.55,9.17,13.88a98.51,98.51,0,0,0,8.29,51.1c26.41,58.41,105.84,73,151.15,27.74,49.58-49.57,32.34-130.93-33.14-156a87.26,87.26,0,0,0-42.19-5.33,61.1,61.1,0,0,1-10.47.4c-6.59-.34-10.66-4.19-11.07-10-.42-6,3.37-10.85,9.67-12,28.84-5.2,56.15-.71,81.22,14.46,30,18.18,48.64,44.78,55.66,79.31C424.87,239.56,425.15,246.88,425.43,253.62Z"
                                                transform="translate(-181.47 -136.5)" />
                                        <path class="cls-2"
                                                d="M334.05,264c0,8.83.06,17.66,0,26.49-.06,6.58-4,9.13-9.83,6.25-10-4.91-20-9.84-29.81-15.14-11.25-6.08-17.52-15.35-17.57-28.59,0-11.64-5.93-20.56-14.42-27.94q-37.7-32.81-75.46-65.54c-.88-.76-1.79-1.5-2.65-2.28-2.82-2.54-3.88-5.55-1.55-8.83,2.21-3.11,5.21-3,8.42-1.37q18.62,9.62,37.29,19.16c28.12,14.42,56.21,28.91,84.39,43.23,14.24,7.23,22.26,18,21.27,34.59C333.72,250.65,334,257.34,334.05,264Z"
                                                transform="translate(-181.47 -136.5)" />
                                </svg> Elsifight Builder</a>
                </div>
        </div>
</header>

templates/layouts/v2_base_header.html
{% load static %}
<header class="p-3 bg-light text-primary mb-4 ">
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom">
        <div  class="container p-2">
            <a href="{% url 'home:looking' request.session.looking_for %}">
                <img src="{% static site.logo %}" height="40" alt="{{ site.name }}">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav m-auto mb-2 mb-md-0">
                    {% for name, path in header_menu.items %}
                    <li class="nav-item">
                        <a href="{{path}}" class="nav-link {% if  request.path == path %} active {% endif %} ">{{ name }}</a>
                    </li>
                    {% endfor %}
                    <li>
                        <a href="{% url 'home:elsifightbuilder' %}" target="_blank" rel="nofollow"
                            class="nav-link {% if  request.path == path %} active {% endif %} "> <svg width="20"
                                height="20" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 243.96 234.86">
                                <defs>
                                    <style>
                                        .cls-1 {
                                            fill: #ef3c65;
                                        }

                                        .cls-2 {
                                            fill: #ef3a65;
                                        }
                                    </style>
                                </defs>
                                <title>Elsifight</title>
                                <path class="cls-1"
                                    d="M425.43,253.62c-.16,59.07-44.16,109.08-102.18,116.75-63.81,8.43-123.56-37.61-131.53-101.22a159.82,159.82,0,0,1-.68-24.94,25.46,25.46,0,0,1,.93-5.91c1.9-6.9,7.21-10.69,13.15-9.55,6.37,1.23,9.88,6.55,9.17,13.88a98.51,98.51,0,0,0,8.29,51.1c26.41,58.41,105.84,73,151.15,27.74,49.58-49.57,32.34-130.93-33.14-156a87.26,87.26,0,0,0-42.19-5.33,61.1,61.1,0,0,1-10.47.4c-6.59-.34-10.66-4.19-11.07-10-.42-6,3.37-10.85,9.67-12,28.84-5.2,56.15-.71,81.22,14.46,30,18.18,48.64,44.78,55.66,79.31C424.87,239.56,425.15,246.88,425.43,253.62Z"
                                    transform="translate(-181.47 -136.5)" />
                                <path class="cls-2"
                                    d="M334.05,264c0,8.83.06,17.66,0,26.49-.06,6.58-4,9.13-9.83,6.25-10-4.91-20-9.84-29.81-15.14-11.25-6.08-17.52-15.35-17.57-28.59,0-11.64-5.93-20.56-14.42-27.94q-37.7-32.81-75.46-65.54c-.88-.76-1.79-1.5-2.65-2.28-2.82-2.54-3.88-5.55-1.55-8.83,2.21-3.11,5.21-3,8.42-1.37q18.62,9.62,37.29,19.16c28.12,14.42,56.21,28.91,84.39,43.23,14.24,7.23,22.26,18,21.27,34.59C333.72,250.65,334,257.34,334.05,264Z"
                                    transform="translate(-181.47 -136.5)" />
                            </svg> Elsifight Builder</a>
                    </li>
                    <li>
                        <a href="{% if alter %} {{alter}} {% else %} {% url 'home:looking' alternat_looking %} {% endif %}"
                            target="_blank"
                            rel="dofollow"
                            class="d-md-none nav-link {% if  request.path == path %} active {% endif %} ">Switch to
                            {{alternat_looking|upper}} </a>
                    </li>
                </ul>

                <a class="d-none d-md-block btn btn-primary btn-sm"
                    href="{% if alter %} {{alter}} {% else %} {% url 'home:looking' alternat_looking %} {% endif %}">Switch
                    to {{alternat_looking|upper}} </a>
            </div>
        </div>
    </nav>
</header>