bio/urls.py
from . import views
from django.urls import path

app_name = 'bio'
urlpatterns = [
 
    path('<str:looking>/category/<str:slug>', views.view_cat, name='view_cat'),
    path('<str:looking>/service/<str:slug>', views.service_details, name='service_details'),
    path('<str:looking>/works/<str:slug>', views.work_details, name='work_details'),
    path('cv/<str:looking>', views.cv, name='cv'),    
    path('cv/<str:looking>/pdf', views.cvpdf, name='cvpdf'),
    
]

bio/views.py
from django.contrib import messages
from django.test import override_settings
import pdfkit
from django.template.loader import get_template
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from bio.helper import get_me_data
from home.decorators import looking_for_required, no_looking_required, set_looking_for
from .models import *
from common.common_processor import site_info, common_process
import platform
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.template.defaultfilters import striptags
from django.conf import settings
# helper function 


def get_verbose_name(instance, field_name):
    """
    Returns verbose_name for a field.
    """
    return instance._meta.get_field(field_name).verbose_name.title()


@set_looking_for
@looking_for_required
def view_cat(request, **kwargs): 
    
    slug = kwargs['slug']
    looking = kwargs['looking']
    me_data = get_me_data(request)
    
    category = ServiceCategory.objects.get(slug=slug)
    me = Me.objects.get(me_for=looking)
    services = category.services.filter(me=me)
    
    
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(reverse('bio:view_cat', args=[str(looking), slug])),        
        'slogan' : f'categorywise service for category {category.name}',
        'description' : f'{striptags(me_data.summary)[:160]}...',
        'topic' : f'Category wise service list that I provide',
        'type' : f'Service List',
        'robots' : f'index, follow'
    }    
    seo_info.update(modify)     

    categoris_of_products = set()
    related_service_by_categories = set()
    for s in services:
        for c in s.category.all():
            if c != category:
                categoris_of_products.add(c)
                for ser in c.services.filter(me=me):
                    related_service_by_categories.add(ser)
    rsbc = [s for s in related_service_by_categories if s not in services]
    context = {
        'services': services,
        'me_data': me_data,
        'category': category,
        'categoris_of_products': list(categoris_of_products),
        'related_service_by_categories': rsbc,
        'site' : seo_info,
        'alter' : reverse('bio:view_cat', args=[str(common_process(request).get('alternat_looking')), slug]) 
        
    }
    return render(request, 'bio/category.html', context=context)


def comparision(service):
    com_data = {}   
    ex_labels = ExtraLabel.objects.filter(l_for = service.me )
    title = []
    description = []
    delivery_time = []
    revision = []
    price = []
    extra = []
    
    for service_option in service.myservice.all():        
        for field in service_option._meta.fields:
            if field.name == 'title':
                title.append(getattr(service_option, field.name, None))
            if field.name == 'description':
                description.append(getattr(service_option, field.name, None))
            if field.name == 'delivery_time':
                delivery_time.append(getattr(service_option, field.name, None))
            if field.name == 'revision':
                revision.append(getattr(service_option, field.name, None))
            if field.name == 'price':
                price.append(getattr(service_option, field.name, None))
       
        el_value = {}  
        for el in service_option.get_extra:
            # value = [soe.value for soe in service_option.get_extra if el.name == soe.label.name] or ['-']
            d = {
                el.label.name : el.value if el.value else '-'
            }            
            el_value.update(d)        
        extra.append(el_value)
    if title:        
        com_data.update({get_verbose_name(service_option, 'title'):title})
    if description:
        com_data.update({get_verbose_name(service_option, 'description'):description})
    if delivery_time:
        com_data.update({get_verbose_name(service_option, 'delivery_time'):delivery_time})
    if revision:
        com_data.update({get_verbose_name(service_option, 'revision'):revision})
    if price:
        com_data.update({get_verbose_name(service_option, 'price'):price})
    
    result = compile(extra)
    for k, v in result.items():
        com_data.update({k:v})   
    
    return com_data

def compile(ls):
    dx = dict()
    for d in ls:
        for k, v in d.items():
            current = dx.get(k, [])  
            current.append(v)
            dx[k] = current
    return dx

@set_looking_for
@looking_for_required
def service_details(request, **kwargs):
    slug = kwargs['slug']
    looking = kwargs['looking']
    service = get_object_or_404(MyService, slug=slug)
    com_data = comparision(service)

    me_data = get_me_data(request)
    
    
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(reverse('bio:service_details', args=[str(looking), slug])),        
        'slogan' : f'Service details of {service.name}',
        'description' : f'{striptags(service.description)[:160]}...',
        'topic' : f'Details about service {service.name}',
        'type' : f'Details of service',
        'robots' : f'index, follow',
        'og_image' : service.get_image.picture.url
    }    
    seo_info.update(modify)   
    
    
    
    context = {
        'me_data': me_data,
        'service': service,
        'com_data': com_data,
        'site' : seo_info,
    }
    return render(request, 'bio/service_detail.html', context=context)


@set_looking_for
@looking_for_required
def work_details(request, **kwargs):
    slug = kwargs['slug']
    looking = kwargs['looking']
    me_data = get_me_data(request)
    work = get_object_or_404(MyWorks, slug=slug)
    
    
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(reverse('bio:work_details', args=[str(looking), slug])),        
        'slogan' : f'Work details of {work.title}',
        'description' : f'{striptags(work.description)[:160]}...',
        'topic' : f'Details about my work {work.title}',
        'type' : f'Details of work',
        'robots' : f'index, follow',
        'og_image' : work.get_image.picture.url if work.get_image else None
    }    
    seo_info.update(modify)   

    context = {
        'me_data': me_data,
        'service': work,
        'site' : seo_info,

    }
    return render(request, 'bio/work_detail.html', context=context)


@set_looking_for
@looking_for_required
def cv(request, **kwargs):

    looking = kwargs['looking']

 
    me_data = get_me_data(request)
    
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(request.path),        
        'slogan' : f'My HTML CV of {looking} sector',
        'description' : f'{striptags(me_data.summary)[:160]}...',
        'topic' : f'{looking} HTML CV ',
        'type' : f'Html CV',
        'robots' : f'index, follow',
        'og_image' : me_data.photo.url 
    }    
    seo_info.update(modify)   
    

    context = {
        'me_data': me_data,
        'interest' : Interest.objects.all(),
        'languge' : Languge.objects.all(),
        'alter' : reverse('bio:cv', args=[str(common_process(request).get('alternat_looking'))]),
        'site' : seo_info,


    }
    return render(request, 'bio/cv.html', context=context)

    

def render_html(request, **kwargs):
    
    me_data = get_me_data(request)    
    #active below for windows development server
    static_url = '%s://%s%s' % (request.scheme,
                                request.get_host(), settings.STATIC_URL)
    # media_url = '%s://%s%s' % (request.scheme,
    #                            request.get_host(), settings.MEDIA_URL)
    # media_link = '%s://%s%s%s' % (request.scheme,
    #                            request.get_host(), settings.STATIC_URL, settings.MEDIA_URL)
    # print(media_link)
    title = '{}_{}_cv.pdf'.format(str(((me_data.title).lower()).replace(' ', '_')), str(kwargs['looking'])) 
    
    context = {
        'me_data': me_data,
        'title' : title,
        'site' : site_info(),
        'interest' : Interest.objects.all(),
        'languge' : Languge.objects.all(),
        'education' : Education.objects.all(),        
    }
    #active below for windows development server
    with override_settings(STATIC_URL=static_url):
        template = get_template('bio/cvpdf.html')
        context = context
        html = template.render(context)
        return html

@set_looking_for
@looking_for_required
def cvpdf(request, **kwargs):
    site = site_info()
    site_email = site.get('email')
    
    
    
    content = render_html(request, **kwargs)
    
    if 'html' in request.GET:
        # Output HTML        
        return HttpResponse(content)
    else: 
        if platform.system() == 'Windows':
            wkhtmltopdf_bin = 'C:\\Program Files (x86)\\wkhtmltopdf\\bin\\wkhtmltopdf.exe'
        elif platform.system() == 'Linux':
            wkhtmltopdf_bin = '/usr/local/bin/wkhtmltopdf'
        else:
            messages.warning(request,f'OS Unknow! Please drop a mail to {site_email}')    
            return  HttpResponseRedirect(reverse('home:home'))
            
        config = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf_bin)
        options = {
            'page-size': 'A4',
            'encoding': 'UTF-8',
            'margin-top': '0.05in',
            'margin-right': '0.05in',
            'margin-bottom': '0.05in',
            'margin-left': '0.05in',            
            'custom-header': [
                ('Accept-Encoding', 'gzip')
            ],
            'cookie': [
                ('cookie-name1', 'cookie-value1'),
                ('cookie-name2', 'cookie-value2'),
            ],
            'outline-depth': 1,
        }        
        pdf = pdfkit.from_string(input=content, output_path=False,
                                options=options, configuration=config)

templates/bio/category.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}

{% block title %}{{ site.slogan }}{% endblock %}
{% block content %}

{% include "layouts/tophero.html" %}
<div class="text-center bg-light o-95 p-3">
  <h1 class="display-5 fw-normal">Service Category: {{category.name}}</h1>
  <div class="p-2">
    <p class="fst-italic">Inform your audience about the services listed here:</p>
    <div class="addthis_inline_share_toolbox_spsh mt-2"></div>
  </div>
</div>
<div class="bg-dark o-95">
  <div class="container">
    <div class="row g-3 p-3">
      {% for service in services %}
      <div class="col-12 col-md-6 d-flex">
        <div class="{% if forloop.counter|divisibleby:2 %} {{service.dark_body_class}} {% else %} {{service.light_body_class}} {% endif %} flex-fill position-relative">
          <a href="{% url 'bio:service_details' request.session.looking_for  service.slug %}"
            class="text-decoration-none text-center {% if forloop.counter|divisibleby:2 %} link-light {% else %} link-dark {% endif %}">
            <div class="d-flex justify-content-between align-items-center fw-bold fs-6 {% if forloop.counter|divisibleby:2 %} {{service.dark_head_class}} {{service.dark_link_class}} {% else %} {{service.light_head_class}} {{service.light_link_class}} {% endif %}">
              <p class="p-4">{{service.name}}</p>
              <p class="p-4">Starting From ${{service.get_starting_price}} </p>
            </div>

            <div class="my-3 px-3">
              <p class="lead">{{service.description|truncatechars:150|striptags}}</p>
            </div>
            <div style="min-height: 250px;">
              <div class="position-absolute bottom-0 start-50 translate-middle-x w-100">
                <div
                  class="{% if forloop.counter|divisibleby:2 %}{{service.light_class}}{% else %}{{service.dark_class}}{% endif %} overflow-hidden col-10 shadow-sm mx-auto"
                  style="height: 250px; border-radius: 21px 21px 0 0;filter: grayscale(100%);">
                  <img src="{% static service.get_image.picture.url %}" class="img-fluid" alt="{{service.name}}">
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>




{% if related_service_by_categories %}
<div class="text-center bg-light o-95 p-3">
  <h1 class="display-5 fw-normal">Related Services</h1>
  <div class="p-2">
    <p class="fst-italic">Services are related to this categoryhas been listed here</p>
  </div>
</div>

<div class="bg-dark o-95">
  <div class="container">
    <div class="row g-3 p-3">
      {% for service in related_service_by_categories %}
      <div class="col-12 col-md-6 d-flex">
        <div class="{% if forloop.counter|divisibleby:2 %} {{service.dark_body_class}} {% else %} {{service.light_body_class}} {% endif %} flex-fill position-relative">
          <a href="{% url 'bio:service_details' request.session.looking_for  service.slug %}"
            class="text-decoration-none text-center {% if forloop.counter|divisibleby:2 %} link-light {% else %} link-dark {% endif %}">
            <div class="d-flex justify-content-between align-items-center fw-bold fs-6 {% if forloop.counter|divisibleby:2 %} {{service.dark_head_class}} {{service.dark_link_class}} {% else %} {{service.light_head_class}} {{service.light_link_class}} {% endif %}">
              <p class="p-4">{{service.name}}</p>
              <p class="p-4">Starting From ${{service.get_starting_price}} </p>
            </div>

            <div class="my-3 px-3">
              <p class="lead">{{service.description|truncatechars:150|striptags}}</p>
            </div>
            <div style="min-height: 250px;">
              <div class="position-absolute bottom-0 start-50 translate-middle-x w-100">
                <div
                  class="{% if forloop.counter|divisibleby:2 %}{{service.light_class}}{% else %}{{service.dark_class}}{% endif %} overflow-hidden col-10 shadow-sm mx-auto"
                  style="height: 250px; border-radius: 21px 21px 0 0;filter: grayscale(100%);">
                  <img src="{% static service.get_image.picture.url %}" class="img-fluid" alt="{{service.name}}">
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endif %}

{% endblock content %}

{% block javascripts %}
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4d95fcae2a2f4222"></script>
<script type="text/javascript">
  var addthis_share = {
    url: "{{request.build_absolute_uri}}",
    title: "The services under category '{{category.name}}' might be helpful to you which was discovered at ",
  }
  var addthis_config = {
    data_track_clickback: false,
    data_track_addressbar: false,
  } 
</script>

{% endblock javascripts %}

templates/bio/cv.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-90">
    <div class="container">
        <div class="row">
            <div class="d-flex col-12 justify-content-between">
                <p data-aos="zoom-in-right" data-aos-duration="2000">Resume</p>                
                <a data-aos="zoom-in-left" data-aos-duration="2000" class="btn btn-warning" href="{% url 'bio:cvpdf' request.session.looking_for %}?download" target="_blank">
                    <svg width="20" height="20" class="me-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="download" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                        <path fill="currentColor" d="M480 352h-133.5l-45.25 45.25C289.2 409.3 273.1 416 256 416s-33.16-6.656-45.25-18.75L165.5 352H32c-17.67 0-32 14.33-32 32v96c0 17.67 14.33 32 32 32h448c17.67 0 32-14.33 32-32v-96C512 366.3 497.7 352 480 352zM432 456c-13.2 0-24-10.8-24-24c0-13.2 10.8-24 24-24s24 10.8 24 24C456 445.2 445.2 456 432 456zM233.4 374.6C239.6 380.9 247.8 384 256 384s16.38-3.125 22.62-9.375l128-128c12.49-12.5 12.49-32.75 0-45.25c-12.5-12.5-32.76-12.5-45.25 0L288 274.8V32c0-17.67-14.33-32-32-32C238.3 0 224 14.33 224 32v242.8L150.6 201.4c-12.49-12.5-32.75-12.5-45.25 0c-12.49 12.5-12.49 32.75 0 45.25L233.4 374.6z"></path>
                    </svg>
                    Download PDF Version
                </a>
            </div>
        </div>
    </div>
</section>

<section class="pt-6 bg-light o-95">
    <div data-aos="fade-up" data-aos-duration="2000" class="container mt-n10 mt-n11 z-2">
        <div class="row justify-content-center">
            <div class="col-12 pt-5">
                <div class="card shadow border-0">
                    
                    <div class="d-block d-md-flex align-items-center bg-darkbeige text-white">
                        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-5 col-12 flex-shrink-0">
                            <img src="{% static me_data.photo.url %}" class="float-start img-fluid" alt="{{me_data.title}}">
                        </div>
                        <div class="col-xxl-10 col-xl-9 col-lg-8 col-md-7 col-12 flex-grow-1 p-3">
                            <div class="d-block d-md-flex justify-content-sm-between">                            
                                <div class="">
                                    <h3 class="mb-1">{{me_data.title}}</h3> 
                                    <h5 class="mb-1">{{site.phone}}</h5>
                                    <p class="mb-1">{{site.email}}</p>
                                    <p class="mb-1">{{site.location}}</p>
                                </div>
                                <div class=""> 
                                    {% for link in me_data.get_cv_links %}
                                    {% for l, i in link.items %}
                                    <li class="list-unstyled">{{i|safe}} {{l}}</li>                                
                                    {% endfor %}
                                    {% endfor %}
                                </div>                                
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-5">
                        <div class="card-text">
                            <h2 class="h5 border-bottom">CAREER SUMMARY</h2>
                            <p class="card-text">{{me_data.summary|safe}} </p>
                        </div>

                        <div class="row card-text d-flex justify-content-between mt-4">
                            <div class="col-lg-8">
                                <div class="card-text">
                                    <h2 class="h-5 border-bottom">REMARKABLE WORK EXPERIENCE</h2>
                                            <div class="resume-timeline position-relative">
                                                {% for we in me_data.work_experience %}
                                                <article class="resume-timeline-item position-relative pb-3 mb-3">
                                                    
                                                    <div class="resume-timeline-item-header mb-2">
                                                        <div class="d-flex justify-content-between">
                                                            <h3 class="resume-position-title font-weight-bold mb-1">{{we.title}}</h3>
                                                            <div class="resume-company-name ms-auto text-end"> <a class="text-decoration-none" href="{% url 'bio:work_details' request.session.looking_for we.related_work.slug %}">{{we.related_work.title}}</a> </div>
                                                        </div><!--//row-->
                                                        <div class="resume-position-time">{{we.period|safe}}</div>
                                                    </div><!--//resume-timeline-item-header-->
                                                    <div class="resume-timeline-item-desc">
                                                        <p>{{we.summary|safe}}</p>
                                                        <h4 class="resume-timeline-item-desc-heading font-weight-bold">Achievements:</h4>
                                                        <p>{{we.achivements|safe}}</p>
                                                        
                                                        <h4 class="resume-timeline-item-desc-heading font-weight-bold">Skills Used:</h4>
                                                        <ul class="list-inline">                                                           
                                                            {% for sin in we.techn_used.all %}    
                                                            <li class="list-inline-item me-0"><span class="badge bg-secondary badge-pill">{{sin.name}}</span></li>                                                            
                                                            {% endfor %}
                                                        </ul>
                                                    </div><!--//resume-timeline-item-desc-->
                                                </article><!--//resume-timeline-item-->
                                                {% endfor %}                                                
                                            </div>
                                            
                                             <!--Timeline-->
                                </div>                               
                            </div>
                            <div class="col-lg-4">
                                <div class="row">
                                <div class="col-12 col-sm-6 col-lg-12">
                                <div class="card-text mb-3">
                                    <h2 class="h-5 border-bottom">SKILLS AND TOOLS </h2>
                                    {% for name, value in me_data.get_cvskillsIn.items %}    
                                    <div class="card-text fw-bold">{{name}}</div>
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" style="width: {{value}}%;" aria-valuenow="{{value}}" aria-valuemin="0" aria-valuemax="100">{{value}}%</div>
                                    </div> 
                                    {% endfor %} 
                                </div>
                                </div>
                                
                                <div class="col-12 col-sm-6 col-lg-12">
                                <div class="card-text mb-3">
                                    <h2 class="h-5 border-bottom">RELATED EDUCATION</h2>
                                    <ul class="list-unstyled">
                                        {% for edu in me_data.get_education %}
                                        <li class="mb-2">
                                            <div class=" h5 fw-bold">{{edu.title}}</div>
                                            <div class="h-5">{{edu.school}}</div>
                                            <div class="text-muted">{{edu.period}}</div>
                                        </li>
                                        {% endfor %}                                       
                                    </ul>
                                </div>
                                <div class="card-text mb-3">
                                    <h2 class="h-5 border-bottom">LANGUAGE</h2>                                    
                                        <ul class="list-unstyled resume-lang-list">
                                            {% for ln in languge %}
                                            <li class="mb-2"><span class=" fw-bold">{{ln.name}}</span> <small class="text-muted fw-normal">({{ln.type}})</small></li>                                                        
                                            {% endfor %}
                                        </ul>                                    
                                </div>
                                <div class="card-text mb-3">
                                    <h2 class="h-5 border-bottom">INTEREST</h2>
                                    
                                        <ul class="list-unstyled resume-lang-list">
                                            {% for i in interest %}
                                            <li class="mb-2"><span class="text-muted fw-normal">{{i.name}}</span></li>
                                            {% endfor %}                                                        
                                        </ul>                                    
                                </div>
                                </div>
                                </div>
                            </div>
                        </div>

                        
                        <div class="d-flex justify-content-between align-items-center p-0 border-top">
                            <p class="card-text">From my wide range of work, only a few are mentioned here to keep the CV page under control. I have worked on many other projects including Drupal, Drupal Commerce, OpenCart, Python, Django, etc. To mention here would add extra pages to this CV, which could be overwhelming. I believe in work rather than show.</p>
                        </div>

                        
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>






{% endblock content %}

{% block javascripts %}

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4d95fcae2a2f4222"></script>
<script type="text/javascript">

    var addthis_share = {
        url: "{{request.build_absolute_uri}}",
        title: "A nice work named '{{service.title}}' found at ",
    }
    var addthis_config = {
        data_track_clickback: false,
        data_track_addressbar: false,
    } 
</script>

{% endblock javascripts %}