bio/urls.py
from . import views
from django.urls import path

app_name = 'bio'
urlpatterns = [
 
    path('<str:looking>/category/<str:slug>', views.view_cat, name='view_cat'),
    path('<str:looking>/service/<str:slug>', views.service_details, name='service_details'),
    path('<str:looking>/works/<str:slug>', views.work_details, name='work_details'),
    path('cv/<str:looking>', views.cv, name='cv'),    
    path('cv/<str:looking>/pdf', views.cvpdf, name='cvpdf'),
    
]

sense/urls.py
from . import views
from django.urls import path


app_name = 'sense'
urlpatterns = [ 
    path('senses/', views.post_list, name='sense_list'),
    path('senses/<str:slug>', views.post_detail, name='sense_detail'),
    path('senses/tag/<str:slug>', views.post_list, name='sense_tag'),       
]

sense/models.py
import random
import string
from django.utils import timezone
from django.conf import settings
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
# from taggit.managers import TaggableManager
from taggit_autosuggest.managers import TaggableManager
from django.template.defaultfilters import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class SensePost(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=252)
    image = models.ImageField(upload_to='featured_image/%Y/%m/%d/', null=True, blank=True) 
    slug = models.SlugField(null=True, blank=True, editable=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sense_posts', editable=False)
    body = RichTextUploadingField()
    
    publish = models.DateTimeField(default=timezone.now, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')    
    tags = TaggableManager() 
    view = models.BigIntegerField(default=0, editable=False)  
    
    
    objects = models.Manager()#default manager
    published = PublishedManager()#Cutom Manager
    
    
    class Meta:
        ordering = ('-publish',)    
             
    def __str__(self) -> str:
        return self.title  
        
        
    def save(self, *args, **kwargs):
        if not self.slug:
            slug_sample = slugify(self.title)            
            if SensePost.objects.filter(slug=slug_sample).exists():
                # Generate a random alphanumeric string of length 6
                random_string = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
                slug_sample = slugify(self.title + ' ' + random_string)
            self.slug = slug_sample
        super(SensePost, self).save(*args, **kwargs)
        
    
    
    
    def get_absolute_url(self):
        return reverse('sense:sense_detail', args=[self.slug])
    
    

sense/views.py
from pprint import pprint
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from sense.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from blog.forms import CommentForm, BlogForm
from taggit.models import Tag
from django.db.models import Count, Q 
from common.common_processor import site_info, common_process
from django.template.defaultfilters import striptags





import requests

def post_list(request, slug=None):
    
 
    context = {}    
    
    query = request.GET.get('q')
    request.session['q'] = ''
    
    posts = SensePost.published.all().order_by('-updated') 
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    tag = None
    if slug:
        tag = get_object_or_404(Tag, slug=slug)
        posts=posts.filter(tags__in=[tag]).order_by('-updated')   
            
    elif query:
        request.session['q'] = query
        posts = posts.filter(Q(title__icontains=query) | Q(tags__name__icontains=query) | Q(body__icontains=query)).order_by('-updated').distinct() 
        
    else:
        posts = posts   
        
    paginator = Paginator(posts, 10)
    page = request.GET.get('page') 
    
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger :
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)  
    
    tags = Tag.objects.all().order_by('id') 
    
    if tag:
        taged_text = f'and tagged with {tag.name}'
    else:
        taged_text = ''
    
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(reverse('sense:sense_list')),        
        'slogan' : f'List of all my senses that can be usefull to you {taged_text}!',
        'description' : f"Here's what I've been able to articulate. This list will continue to grow as long as I live. The purpose is to help you.",
        'topic' : f'Blogging',
        'type' : f'Blog',
        'robots' : f'index, follow',
        'tag' : f'Blog, blogging, sense, python, django, web development, fashion designing, technicale fahion, clo3D, apparel sourcing'
    }    
    seo_info.update(modify)   
    
    
    context['posts'] = posts
    context['pages'] = page    
    context['tag'] = tag   
    context['tags'] = tags   
    context['site'] = seo_info      
    return render(request, 'sense/senses.html', context)

def post_detail(request, slug):  
    
    request.session['q'] = ''
    
    query = request.GET.get('q')
    
    if query:
        request.session['q'] = query
        return HttpResponseRedirect(reverse('sense:sense_list') + '?q=' + query)
       
    post = get_object_or_404(SensePost, slug=slug, status='published')
    post.view += 1
    post.save()
    
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_senses = SensePost.published.filter(tags__in = post_tags_id).exclude(id=post.id)
    similar_senses = similar_senses.annotate(same_tags = Count('tags')).order_by('-same_tags', '-publish')[:6] 
    tags = Tag.objects.all()    
    
    tag_list = str([tag.name for tag in post.tags.all()]).replace('[', '').replace(']', '')
    seo_info = site_info() 
    modify = {
        'canonical' : request.build_absolute_uri(reverse('sense:sense_detail', args=[str(slug)])),        
        'slogan' : f'{post.title[:80]}...',
        'description' : f"{striptags(post.body)[:160]}...",
        'topic' : f'{tag_list}',
        'type' : f'Blog',
        'robots' : f'index, follow',
        'tag' : f'Blog, blogging, sense, python, django, web development, fashion designing, technicale fahion, clo3D, apparel sourcing',
        'og_image' : post.image.url if post.image else seo_info['og_image']
        
    }    
    seo_info.update(modify)   
    
    
    context = {
        'post':post,
        'tags' : tags,
        'similar_senses':similar_senses,
        'site' : seo_info    
    }             
    
    return render(request, 'sense/post_detail.html', context = context)

templates/sense/post_detail.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}

{% block stylesheets %}




  {% endblock stylesheets %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-95">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center text-danger my-4">
                <div class="mb-4">
                    / {% for tag in tags %}
                    <a href="{% url 'sense:sense_tag' tag.slug %}"
                        class="link-secondary text-decoration-none">
                        {{tag.name|upper}}
                    </a> /
                    {% endfor %}
                </div>
                <div class="d-block mb-4" style="position: relative;">
                    <h2 class="card-title h5 st-font-size d-block">
                        <a class="link-danger text-decoration-none" href="{{ post.get_absolute_url }}">
                            {{ post.title|upper }}
                        </a> 
                    </h2>
                    <div class="sense-font-image d-none d-md-block">{{ post.title.0 }}</div>
                </div>
                
                <div class="mb-4">
                    <div class="text-muted">
                        Published on {{ post.publish.date }} by <strong>{{ post.author.username  }}</strong>                        
                    </div>
                </div>               
            </div>
        </div>
    </div>
</section>

<section class="pt-6 bg-light o-95">
    <div class="container mt-n10 mt-n11 z-2 ">
        <div class="row justify-content-center align-items-center">
            <div class=" card shadow col-12 p-5 o-90">
                <div class="col-12 col-md-9 mx-auto">
                    <div style="position: relative;">
                    <div class="sense-font-image d-none d-md-block">{{ post.title.0 }}</div>
                </div>
                <div class="mb-4 text-end border-bottom">
                    TAGGED: 
                    / {% for tag in post.tags.all %}
                    <a href="{% url 'sense:sense_tag' tag.slug %}"
                        class="link-secondary text-decoration-none">
                        {{tag.name|upper}}
                    </a> /
                    {% endfor %}
                </div>
                    <div class="card border-0 pb-8">   
                        <div class="card-body p-0">                            
                            <div class="card-text my-4 " style="font-size: 1.6rem; position:relative;">{{ post.body|safe }}</div>
                            <div class="text-center pt-5">
                                <div class="my-3">
                                    <h3>Share Sense To:</h3>
                                </div>
                                <div class="addthis_inline_share_toolbox_spsh mt-2"></div>
                            </div>    
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div
                    class="col-12 d-block d-sm-flex justify-content-between p-2">
                    <div>
                        {% if post.get_previous_by_publish %}
                        <div class="previous">
                            <a class="d-block" href="{% url 'sense:sense_detail' post.get_previous_by_publish.slug %}">&larr; Previous
                                Posts</a>
                            <a class="d-block" href="{% url 'sense:sense_detail' post.get_previous_by_publish.slug %}">{{post.get_previous_by_publish.title}}</a>
                        </div>
                        {% endif %}
                    </div>
                    <div>
                        {% if post.get_next_by_publish %}
                        <div class="next">
                            <a class="d-block" href="{% url 'sense:sense_detail' post.get_next_by_publish.slug %}">Next Posts &rarr;</a>
                            <a class="d-block" href="{% url 'sense:sense_detail' post.get_next_by_publish.slug %}">{{post.get_next_by_publish.title}}</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
            <div class="card shadow col-12 p-5 mt-4 o-90">
                <div class="card-header mb-5">
                    <h3>Similar Senses</h3>
                </div>
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for sense in similar_senses %}
                    <div class="col d-flex">
                        <div class="card bg-lgreen shadow-sm flex-fill overflow-hidden">
                            {% if  sense.image %}
                            <img src="{% static blog.image.url %}" class="img-fluid" alt="{{sense.title|striptags }}">
                            {% else %}
                            {% endif %}
                            <div class="card-title px-2 mb-0 border-bottom py-2">
                                {{sense.title|striptags|upper}}
                                <div class="sense-font-image d-none d-md-block" style="left: -0.5rem;">{{ sense.title.0 }}</div>
                            </div>
                            <div class="card-body pt-0">
                                {{sense.body|striptags|safe|truncatechars:150}}
                                <div class="d-sm-flex d-block justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-primary" href="{{sense.get_absolute_url}}">Read On</a>
                                    </div>
                                    <div class="text-muted">{{sense.view}} views</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

{% block javascripts %}

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4d95fcae2a2f4222"></script>
<script type="text/javascript">

    var addthis_share = {
        url: "{{request.build_absolute_uri}}",
        title: "{{post.title}} ",
    }
    var addthis_config = {
        data_track_clickback: false,
        data_track_addressbar: false,
    } 
</script>



{% endblock javascripts %}

templates/sense/senses.html
{% extends "layouts/v2_base.html" %}
{% load static %}
{% load custom_tags %}



  {% block stylesheets %}



  {% endblock stylesheets %}

{% block title %}{{site.slogan}}{% endblock %}
{% block content %}
{% include "layouts/topherocv.html" %}
<section class="pb-6 pb-lg-8 bg-dark text-white o-95">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-12 text-center text-danger my-4">
                <h1 class="mb-4">Latest Senses</h1>                
                {% if tag %}
                <h2 class="mb-4 text-secondary text-center p-2 ">Sences tagged  with "{{ tag.name }}"</h2>
                {% endif %}
            </div>
        </div>
    </div>

</section>

<section class="pt-6 bg-light o-95">
    <div class="container mt-n10 mt-n11 z-2">
        <div class="row justify-content-center align-items-center">
            <div class=" card shadow col-12 p-5 o-90">
                <div class="row">
                <div class="col-md-4 col-lg-3 ">
                    <nav class="navbar navbar-expand-md navbar-light border-bottom">
                    <div class="w-100" > 
                        <button class="w-100 navbar-toggler mb-3 bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#tagCollapse"
                            aria-controls="tagCollapse" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="tagCollapse">                            
                            <ul class="navbar-nav nav-pills flex-column mb-2 mb-md-0 w-100">
                                {% for tag in tags %}
                                <li>
                                    <a href="{% url 'sense:sense_tag' tag.slug %}" class="nav-link link-danger fw-bold ps-0 {% if tag.slug in segments %} ps-2 bg-danger text-white active {% endif %}">
                                    #{{tag.name|upper}}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                      </div>
                    </nav>
                    <form method="get" action="" class="row g-1 justify-content-center align-items-center text-center mt-2">       
                        <div class="input-group mb-3">
                            <input type="text" name="q" class="form-control" value="{{request.session.q}}" aria-label="Search senses..." placeholder="Search senses..." aria-describedby="button-q">
                            <button type="submit" id="button-q" class="btn btn-secondary">Search</button>
                        </div>            
                    </form> 
                </div>
                {% if posts %}
                <div class="col-md-8 col-lg-9 mx-auto">
                    {% for post in posts %}
                    <div class="card border-0   pb-8">
                        <div class="d-block" style="position: relative;">
                            <h2 class="card-title h5 st-font-size d-block">
                                <a class="link-danger text-decoration-none" href="{{ post.get_absolute_url }}">
                                    {{ post.title|upper }}
                                </a>

                            </h2>
                            <div class="sense-font-image d-none d-md-block">{{ post.title.0 }}</div>
                        </div>

                        <div class="card-body p-0 pb-2">
                            <div class="justify-content-between border-top border-bottom border-2 border-danger pt-2">
                                <div class="mb-2">
                                    <div class="text-muted">
                                        Published on {{ post.publish.date }} by <strong>{{ post.author.username  }}</strong>
                                        <span>
                                            / {% for tag in post.tags.all %}
                                            <a href="{% url 'sense:sense_tag' tag.slug %}"
                                                class="badge bg-secondary text-decoration-none link-blight">
                                                {{tag.name}}
                                            </a> /
                                            {% endfor %}
                                        </span>
                                    </div>
                                </div>

                            </div>
                            <div class="card-text my-4 " style="font-size: 1.6rem; position:relative;">{{ post.body|striptags|safe|truncatechars:500 }}</div>
                            
                            
                        </div>
                        <div class=" d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-lg btn-danger">Read On</a>
                            </div>
                            <div class="text-muted">{{post.view}} views</div>
                        </div>

                    </div>

                    {% endfor %}
                    {% include "layouts/pagination.html" with page=posts %}
                </div>
                {% else %}
                <div class="col-md-8 col-lg-9 mx-auto">
                    <div class="alert alert-primary" role="alert">No Senses Found!</div>
                </div>
                {% endif %}
            </div>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

{% block javascripts %}

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4d95fcae2a2f4222"></script>
<script type="text/javascript">

    var addthis_share = {
        url: "{{request.build_absolute_uri}}",
        title: "A nice work named '{{service.title}}' found at ",
    }
    var addthis_config = {
        data_track_clickback: false,
        data_track_addressbar: false,
    } 
</script>

{% endblock javascripts %}